kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: api-user-view-binding
  namespace: apinamespace
subjects:
- kind: User
  name: api-dev@OTAPRD517ops.onmicrosoft.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io