apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: poi-ingress
  namespace: apinamespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: poi
          servicePort: 80